export const movies = [
    {
        slug: "sikandar",
        year: 2025,
        title: "Sikandar",
        cast: ["Salman Khan", "Rashmika Mandanna", "Sathyaraj", "Kajal Aggarwal", "Sharman Joshi"],
        director: "AR Murugadoss",
        poster: "/images/movie/sikandar.png",
        category: "upcoming movies",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "farrey",
        year: 2023,
        title: "Farrey",
        cast: ["Alizeh", "Ronit Roy", "Sahil Mehta", "Zeyn Shaw", "Prasanna Bisht"],
        director: "Soumendra Padhi",
        poster: "/images/movie/farrey.png",
        category: "upcoming movies",
        trailer: "/images/home/farrey.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "kisi-ka-bhai-kisi-ki-jaan",
        year: 2023,
        title: "Kisi Ka Bhai Kisi Ki Jaan",
        cast: ["Salman Khan", "Pooja Hegde", "Venkatesh", "Jagapathi Babu"],
        director: "Farhad Samji",
        poster: "/images/movie/kiss-ka-bhai.png",
        category: "released",
        trailer: "/images/home/kiss-ka-bhai.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "antim-the-final-truth",
        year: 2021,
        title: "Antim: The Final Truth",
        cast: ["Salman Khan", "Aayush Sharma", "Mahima Makwana", "Jisshu Sengupta"],
        director: "Mahesh Manjrekar",
        poster: "/images/movie/antim.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "radhe",
        year: 2021,
        title: "Radhe",
        cast: ["Salman Khan", "Disha Patani", "Randeep Hooda", "Jackie Shroff"],
        director: "Prabhu Deva",
        poster: "/images/movie/radhe.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "kaagaz",
        year: 2021,
        title: "Kaagaz",
        cast: ["Pankaj Tripathi", "Monal Gajjar", "Amar Upadhyay", "Tina Ahuja", "Lankesh"],
        director: "Satish Kaushik",
        poster: "/images/movie/kaagaz.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "dabangg-3",
        year: 2019,
        title: "Dabangg 3",
        cast: ["Salman Khan", "Sonakshi Sinha", "Saiee Manjrekar", "Sudeepa", "Arbaaz Khan"],
        director: "Prabhu Deva",
        poster: "/images/movie/kaagaz.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "bharat",
        year: 2019,
        title: "Bharat",
        cast: ["Salman Khan", "Katrina Kaif", "Disha Patani", "Sunil Grover", "Jackie Shroff"],
        director: "Ali Abbas Zafar",
        poster: "/images/movie/bharat.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "notebook",
        year: 2019,
        title: "Notebook",
        cast: ["Zaheer Iqbal", "Pranutan Bahl"],
        director: "Nitin Kakkar",
        poster: "/images/movie/notebook.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "loveyatri",
        year: 2018,
        title: "Loveyatri",
        cast: ["Aayush Sharma", "Warina Hussain"],
        director: "Abhiraj Minawala",
        poster: "/images/movie/loveyatri.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "race-3",
        year: 2018,
        title: "Race 3",
        cast: ["Anil Kapoor", "Salman Khan", "Bobby Deol", "Jacqueline Fernandez", "Daisy Shah", "Saqib Saleem"],
        director: "Remo D'Souza",
        poster: "/images/movie/race3.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "tubelight",
        year: 2017,
        title: "Tubelight",
        cast: ["Salman Khan", "Sohail Khan", "Om Puri", "Matin Rey Tangu", "Zhu Zhu"],
        director: "Kabir Khan",
        poster: "/images/movie/tubelight.png",
        category: "released",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "hero",
        year: 2015,
        title: "Hero",
        cast: ["Sooraj Pancholi", "Athiya Shetty", "Aditya Pancholi"],
        director: "Nikhil Advani",
        poster: "/images/movie/hero.png",
        category: "upcoming movies",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "bajrangi-bhaijaan",
        year: 2015,
        title: "Bajrangi Bhaijaan",
        cast: ["Salman Khan", "Harshaali Malhotra", "Kareena Kapoor Khan", "Nawazuddin Siddiqui"],
        director: "Kabir Khan",
        poster: "/images/movie/bajrangi.png",
        category: "upcoming movies",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "dr-cabbie",
        year: 2014,
        title: "Dr. Cabbie",
        cast: ["Vinay Virmani", "Kunal Nayyar", "Adrianne Palicki"],
        director: "Jean-François Pouliot",
        poster: "/images/movie/cabbie.png",
        category: "upcoming movies",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    },
    {
        slug: "chillar-party",
        year: 2011,
        title: "Chillar Party",
        cast: ["Shriya Sharma", "Sanath Menon", "Rohan Grover", "Naman Jain", "Aarav Khanna", "Vishesh Tiwari", "Shashank Shende"],
        director: ["Nitesh Tiwari", "Vikas Bahl"],
        poster: "/images/movie/chillar-party.png",
        category: "upcoming movies",
        trailer: "/images/home/hero.mp4",
        media: [
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/sikandar.png" },
            { type: "image", url: "/images/movie/farrey.png" },
            { type: "image", url: "/images/movie/kiss-ka-bhai.png" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "video", url: "/images/home/hero.mp4" },
            { type: "image", url: "/images/movie/antim.png" },
            { type: "image", url: "/images/movie/radhe.png" },
            { type: "image", url: "/images/movie/kaagaz.png" },
        ]
    }
];
