export const movies = [
    {
        slug: "sikandar",
        year: 2025,
        title: "Sikandar",
        cast: ["Salman Khan", "Rashmika Mandanna", "Sathyaraj", "Kajal Aggarwal", "Sharman Joshi"],
        produced: "Sajid Nadiadwala",
        director: "A.R. Murugadoss",
        poster: "/images/movie/sikandar.png",
        category: "upcoming movies",
        synopsis: `Sikandar follows the journey of a man who overcomes all hurdles that life throws his way just so that he can alleviate the plight of the less fortunate and those in need of his help. His transition from a nonchalant man to a selfless man, inspired by his wife, makes him emerge as a beacon of hope for those ensnared in darkness.`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=diQPz4y6bWA" },
            { url: "https://www.youtube.com/watch?v=GvKXUpXwd_M" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/sikandar.png",
        ]
    },
    {
        slug: "farrey",
        year: 2023,
        title: "Farrey",
        cast: ["Alizeh", "Ronit Roy", "Sahil Mehta", "Zeyn Shaw", "Prasanna Bisht"],
        produced: "Atul Agnihotri, Alvira Khan, Sunir Kheterpal, Nikhil Namit, Y. Ravi Shankar, Naveen Yerneni, Salman Khan",
        director: "Soumendra Padhi",
        poster: "/images/movie/farrey.png",
        category: "upcoming movies",
        synopsis: `Niyati, an orphan prodigy, living under the care of her warden in a local orphanage in Delhi, becomes the national level topper in the 10th board exams and secures admission in an elite school on scholarship. There she is lured by her rich friends to help them cheat in exams by developing elaborate methods and gets pulled into a cheating racket with increasingly higher risks and even higher rewards. But she may lose much more than she gains.`,
        teaser: "",
        trailer: "/images/home/farrey.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=Dpgy-Juf8zk" },
        ],
        galleryCover: [
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/sikandar.png",
            "/images/movie/farrey.png",
        ]
    },
    {
        slug: "kisi-ka-bhai-kisi-ki-jaan",
        year: 2023,
        title: "Kisi Ka Bhai Kisi Ki Jaan",
        cast: ["Salman Khan", "Pooja Hegde", "Venkatesh"],
        produced: "Salman Khan",
        director: "Farhad Samji",
        poster: "/images/movie/kiss-ka-bhai.png",
        category: "released",
        synopsis: `Salman Khan is a self-appointed vigilante committed to the cause of keeping the society crime-free. His younger brothers set him up with a woman similar to his previous love interest. What follows is a series of events that takes all of them across the length of the country and various revelations with all the elements of a wholesome entertainer.`,
        teaser: "",
        trailer: "/images/home/kiss-ka-bhai.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=VEDhJIl8kNk&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=3" },
            { url: "https://www.youtube.com/watch?v=w0ECti8sCp8&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=9" },
            { url: "https://www.youtube.com/watch?v=o6wwdVOQhjI&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=10" },
            { url: "https://www.youtube.com/watch?v=m5LFWvwToHU&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=18" },
            { url: "https://www.youtube.com/watch?v=vGfTqxdR1H0&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=19" },
            { url: "https://www.youtube.com/watch?v=DJhxnA8ELlk&list=PLofFoQnZAD2HKdDB6wTn7Wcs601_ZPOa6&index=23" },
        ],
        galleryCover: [
            "/images/movie/sikandar.png",
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
        ]
    },
    {
        slug: "antim-the-final-truth",
        year: 2021,
        title: "Antim: The Final Truth",
        cast: ["Salman Khan", "Aayush Sharma", "Mahima Makwana", "Jisshu Sengupta", "Waluscha De Sousa"],
        produced: "Salman Khan",
        director: "Mahesh Manjrekar",
        poster: "/images/movie/antim.png",
        category: "released",
        synopsis: `Rahulya is a penniless village boy with a dream of being Pune’s biggest don. His closest friend
Ganya is beside him through it all, while his parents shun their violent son. A hot-headed boy,
his love for the local chaiwali Manda does nothing to cool him down. Policeman Rajveer Singh
watches this unassuming boy rise up the ranks, frustrated as Rahulya manages to use his
connections to slip out of police custody time and again. With Rajveer at his heels, Rahulya still
manages to easily reach the top, but soon loses sight of why he ever wanted to ascend the
ranks. As the power goes to his head, he ruins relations with his family and ladylove. His only
solace is Ganya and Sidhu, an orphan boy he adopts. Will Rajveer manage to bring Rahulya
down, or will his own past catch up with him first? Only at the end is the final truth revealed.
`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=7-E9jBVF2Ng&list=PLofFoQnZAD2GbZ7q_z4WGULuFzxxaoU08&index=6" },
            { url: "https://www.youtube.com/watch?v=Pl0pRLY9ZZk&list=PLofFoQnZAD2GbZ7q_z4WGULuFzxxaoU08&index=9" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/antim.png",
        ]
    },
    {
        slug: "radhe",
        year: 2021,
        title: "Radhe",
        cast: ["Salman Khan", "Disha Patani", "Randeep Hooda", "Jackie Shroff"],
        produced: "Salman Khan, Sohail Khan, Atul Agnihotri, Nikhil Namit",
        director: "Prabhu Deva",
        poster: "/images/movie/radhe.png",
        category: "released",
        synopsis: `The drug mafia has increased in India, where more and more youngsters are addicted to drugs and taking their lives. The Mumbai police decides to get suspended officer Radhe (Salman Khan) on duty to clean the city. Radhe joins soon and firstly makes two rival groups of Dagdu Dada and Dilwar to join hands as they are against the drug business and will help him clean the city. Radhe's reporting officer is funny, ACP Avinash Abhyankar, who runs away with Radhe's credits while Radhe loves Avinash's sister Dia and pretends to be an upcoming model. Rana the drug lord who has landed in Mumbai and forces people to sell drugs and gets Dilwar killed from his brother Mansoor who works for him, Radhe manages to trace Rana which starts a long cat and mouse race between them. `,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=r7MJ2gaIwsE&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=5" },
            { url: "https://www.youtube.com/watch?v=dmeryUOm5VM&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=7" },
            { url: "https://www.youtube.com/watch?v=7tKwYnKfuMY&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=8" },
            { url: "https://www.youtube.com/watch?v=qMx2MoYwxms&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=13" },
            { url: "https://www.youtube.com/watch?v=vt4gyzr0ib8&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=17" },
            { url: "https://www.youtube.com/watch?v=FPQs4u2d_Ik&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=21" },
            { url: "https://www.youtube.com/watch?v=7yeZzwK8kwY&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=25" },
            { url: "https://www.youtube.com/watch?v=dda6pqEpdeQ&list=PLofFoQnZAD2FGyj1lEdrj5bjt-MHzZ6sm&index=27" },
        ],
        galleryCover: [
            "/images/movie/sikandar.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/radhe.png",
        ]
    },
    {
        slug: "kaagaz",
        year: 2021,
        title: "Kaagaz",
        cast: ["Pankaj Tripathi", "Monal Gajjar", "Amar Upadhyay", "Tina Ahuja", "Lankesh"],
        produced: "",
        director: "Satish Kaushik",
        poster: "/images/movie/kaagaz.png",
        category: "released",
        synopsis: ``,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
        ],
        galleryCover: [
        ]
    },
    {
        slug: "dabangg-3",
        year: 2019,
        title: "Dabangg 3",
        cast: ["Salman Khan", "Sonakshi Sinha", "Saiee Manjrekar", "Sudeepa", "Arbaaz Khan"],
        produced: "Salman Khan, Arbaaz Khan, Nikhil Dwivedi",
        director: "Prabhu Deva",
        poster: "/images/movie/kaagaz.png",
        category: "released",
        synopsis: `More beefed-up, worked up and dangerous than ever, Chulbul Pandey, now the tough-as-nails police superintendent of Tundla city in Uttar Pradesh, finds himself juggling career and family after bringing down unscrupulous Baccha Singh's empire in Dabangg 2 (2012). However, as the past comes back to haunt him in the shape of the wicked old nemesis, Bali Singh. `,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=Vl0UaDiJ6Hw&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy" },
            { url: "https://www.youtube.com/watch?v=BUHIooHBj9A&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=3" },
            { url: "https://www.youtube.com/watch?v=HMeSSSmHomc&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=7" },
            { url: "https://www.youtube.com/watch?v=M0kXQZdWOuA&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=17" },
            { url: "https://www.youtube.com/watch?v=KsRgMfVfbbA&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=19" },
            { url: "https://www.youtube.com/watch?v=zJXBXSE9KO4&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=22" },
            { url: "https://www.youtube.com/watch?v=hEsOHbIg7w8&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=25" },
            { url: "https://www.youtube.com/watch?v=SItUtPrEX4M&list=PLofFoQnZAD2Ge5Tg1UfGDPSS9yxokWyKy&index=30" },
        ],
        galleryCover: [
            "/images/movie/sikandar.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/farrey.png",
        ]
    },
    {
        slug: "bharat",
        year: 2019,
        title: "Bharat",
        cast: ["Salman Khan", "Katrina Kaif", "Disha Patani", "Sunil Grover", "Jackie Shroff"],
        produced: "",
        director: "Ali Abbas Zafar",
        poster: "/images/movie/bharat.png",
        category: "released",
        synopsis: ``,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
        ],
        galleryCover: [
        ]
    },
    {
        slug: "notebook",
        year: 2019,
        title: "Notebook",
        cast: ["Zaheer Iqbal", "Pranutan Bahl"],
        produced: "",
        director: "Nitin Kakkar",
        poster: "/images/movie/notebook.png",
        category: "released",
        synopsis: ``,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=bSA8Zuu7icE&list=PLofFoQnZAD2Fckf2uddImjOBss59DynoH&index=8" },
            { url: "https://www.youtube.com/watch?v=QctNjpNYOH8&list=PLofFoQnZAD2Fckf2uddImjOBss59DynoH&index=9" },
            { url: "https://www.youtube.com/watch?v=J7PFVcRzblA&list=PLofFoQnZAD2Fckf2uddImjOBss59DynoH&index=10" },
            { url: "https://www.youtube.com/watch?v=qQVDU4lwSII&list=PLofFoQnZAD2Fckf2uddImjOBss59DynoH&index=18" },
            { url: "https://www.youtube.com/watch?v=qQVDU4lwSII&list=PLofFoQnZAD2Fckf2uddImjOBss59DynoH&index=18" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/notebook.png",
        ]
    },
    {
        slug: "loveyatri",
        year: 2018,
        title: "Loveyatri",
        cast: ["Aayush Sharma", "Warina Hussain"],
        produced: "Salman Khan",
        director: "Abhiraj Minawala",
        poster: "/images/movie/loveyatri.png",
        category: "released",
        synopsis: `Sushrut, a garba teacher, falls in love with NRI girl Michelle when she visits town during festival`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=T2hPPkgdUWw" },
            { url: "https://www.youtube.com/watch?v=mczUShOM2nk" },
            { url: "https://www.youtube.com/watch?v=i0nF2yaowrw" },
            { url: "https://www.youtube.com/watch?v=pkcEGCeOGAs" },
            { url: "https://www.youtube.com/watch?v=fSvhDShe7oQ" },
        ],
        galleryCover: [
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/farrey.png",
            "/images/movie/loveyatri.png",
        ]
    },
    {
        slug: "race-3",
        year: 2018,
        title: "Race 3",
        cast: ["Salman Khan", "Anil Kapoor", "Bobby Deol", "Jacqueline Fernandez", "Daisy Shah"],
        produced: "Salman Khan",
        director: "Remo D'Souza",
        poster: "/images/movie/race3.png",
        category: "released",
        synopsis: `Race 3 as its predecessors is an internationally mounted saga of a family that deals in borderline crime but is ruthless and vindictive to the core. A world with twists and turns at every nook and corner, which will take the audience by surprise with its sheer unpredictability. Characters change their characteristics at the blink of an eye as the story rushes towards a high-octane climax with betrayal, fast guns, fast cars, and sleek action never seen before on the Indian screen. Action and drama that leads to a shocking twist in the climax that takes your breath away.`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=u4jyLpmIdqw&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=31" },
            { url: "https://www.youtube.com/watch?v=tlMYVJV7YHM&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=32" },
            { url: "https://www.youtube.com/watch?v=zmXmqNkeJ14&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=37" },
            { url: "https://www.youtube.com/watch?v=H196nYaRmRY&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=40" },
            { url: "https://www.youtube.com/watch?v=TLs004_sMqM&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=42" },
            { url: "https://www.youtube.com/watch?v=UbrDz8Fnks4&list=PLofFoQnZAD2Fdqp8vB_oi4gGgMkdwCofa&index=43" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/race3.png",
        ]
    },
    {
        slug: "tubelight",
        year: 2017,
        title: "Tubelight",
        cast: ["Salman Khan", "Sohail Khan", "Om Puri"],
        produced: "Salman Khan, Kabir Khan, Salma Khan",
        director: "Kabir Khan",
        poster: "/images/movie/tubelight.png",
        category: "released",
        synopsis: `A story of two brothers set during the Sino-Indian war, 1962: the younger one who's at war at the borders and the elder who's at war with his own world.

`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=dkWBLXnFuQk&list=PLofFoQnZAD2HuiZX69CtZ8w46VsIxI28v&index=12" },
            { url: "https://www.youtube.com/watch?v=OHms7Zx_3TE&list=PLofFoQnZAD2HuiZX69CtZ8w46VsIxI28v&index=15" },
            { url: "https://www.youtube.com/watch?v=uUQLrFhe5WE&list=PLofFoQnZAD2HuiZX69CtZ8w46VsIxI28v&index=16" },
            { url: "https://www.youtube.com/watch?v=OY2RTlnPDEU&list=PLofFoQnZAD2HuiZX69CtZ8w46VsIxI28v&index=27" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/tubelight.png",
        ]
    },
    {
        slug: "hero",
        year: 2015,
        title: "Hero",
        cast: ["Sooraj Pancholi", "Athiya Shetty", "Aditya Pancholi"],
        produced: "Salman Khan, Subhash Ghai",
        director: "Nikhil Advani",
        poster: "/images/movie/hero.png",
        category: "upcoming movies",
        synopsis: `An adrenaline junkie walks away from a whirlwind romance and embraces a new life as a thief, though he soon finds himself pursued by veteran police officer and engaged in a turf war with a local gangster.`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=j3cWyRmapdg" },
            { url: "https://www.youtube.com/watch?v=O926knS3XEU" },
            { url: "https://www.youtube.com/watch?v=DAcgSUyLj90" },
            { url: "https://www.youtube.com/watch?v=4YkvseTzuXk" },
            { url: "https://www.youtube.com/watch?v=4YkvseTzuXk" },
            { url: "https://www.youtube.com/watch?v=aMy_uOJu2_c" },
            { url: "https://www.youtube.com/watch?v=hx-hjh3BQuw" },
            { url: "https://www.youtube.com/watch?v=V1BQj4nb_I4" },
            { url: "https://www.youtube.com/watch?v=jMSHTNpO6JY" },
            { url: "https://www.youtube.com/watch?v=CFD0BUFY0Y8" },
            { url: "https://www.youtube.com/watch?v=3xXYuS5H-Q8" },
            { url: "https://www.youtube.com/watch?v=-PLTEwAdoKA" },
            { url: "https://www.youtube.com/watch?v=H0BCcI_T1_w" },
            { url: "https://www.youtube.com/watch?v=EG1aTIFSD8A" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/hero.png",
        ]
    },
    {
        slug: "bajrangi-bhaijaan",
        year: 2015,
        title: "Bajrangi Bhaijaan",
        cast: ["Salman Khan", "Harshaali Malhotra", "Kareena Kapoor Khan", "Nawazuddin Siddiqui"],
        produced: "Salman Khan, Rockline Venkatesh, Kabir Khan",
        director: "Kabir Khan",
        poster: "/images/movie/bajrangi.png",
        category: "upcoming movies",
        synopsis: `A 5-year-old girl from Pakistan gets separated from her mother at an Indian railway station. Lost and hungry, she finds shelter at the home of Pawan, an ardent devotee of Hanuman, hailing from a robust wrestling family. Bajrangi Bhaijaan is the moving story of Pavan's quest to unite the child with her parents against all odds. Set against the backdrop of colourful Chandni Chowk, the film travels from the heartland of Punjab, through the deserts of Rajasthan, and over the snow-capped mountains of Kashmir. Bajrangi Bhaijaan tells the story of how Pavan, who moved heaven and earth to fulfil the promise he made to the girl from across the border.`,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
            { url: "https://www.youtube.com/watch?v=VXzUue3v20k" },
            { url: "https://www.youtube.com/watch?v=fpwmbYdJbQA" },
            { url: "https://www.youtube.com/watch?v=iTnNWLawjgo" },
            { url: "https://www.youtube.com/watch?v=1xOcQEa7bx0" },
            { url: "https://www.youtube.com/watch?v=yu7AHhrPbcY" },
            { url: "https://www.youtube.com/watch?v=jiQz6SIlw5M" },
            { url: "https://www.youtube.com/watch?v=siSXwyXtjiU" },
            { url: "https://www.youtube.com/watch?v=xsfvTLhOAGQ" },
            { url: "https://www.youtube.com/watch?v=QihJw8c0eCU" },
            { url: "https://www.youtube.com/watch?v=fn2bpVLUoJs" },
            { url: "https://www.youtube.com/watch?v=-W132TEnvZU" },
            { url: "https://www.youtube.com/watch?v=dWQkPeajgj8" },
            { url: "https://www.youtube.com/watch?v=Q1zTCmyoKig" },
            { url: "https://www.youtube.com/watch?v=YFbsvugPlVo" },
            { url: "https://www.youtube.com/watch?v=2-hTE4MhPuQ" },
            { url: "https://www.youtube.com/watch?v=HanwrCgOJ_A" },
            { url: "https://www.youtube.com/watch?v=YasKpC-Nag0" },
        ],
        galleryCover: [
            "/images/movie/farrey.png",
            "/images/movie/kiss-ka-bhai.png",
            "/images/movie/bajrangi.png",
        ]
    },
    {
        slug: "dr-cabbie",
        year: 2014,
        title: "Dr. Cabbie",
        cast: ["Vinay Virmani", "Kunal Nayyar", "Adrianne Palicki"],
        produced: "",
        director: "Jean-François Pouliot",
        poster: "/images/movie/cabbie.png",
        category: "upcoming movies",
        synopsis: ``,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
        ],
        galleryCover: [
        ]
    },
    {
        slug: "chillar-party",
        year: 2011,
        title: "Chillar Party",
        cast: ["Shriya Sharma", "Sanath Menon", "Rohan Grover", "Naman Jain", "Aarav Khanna", "Vishesh Tiwari", "Shashank Shende"],
        produced: "",
        director: ["Nitesh Tiwari", "Vikas Bahl"],
        poster: "/images/movie/chillar-party.png",
        category: "upcoming movies",
        synopsis: ``,
        teaser: "",
        trailer: "/images/home/hero.mp4",
        media: [
        ],
        galleryCover: [
        ]
    }
];


